### ISSUE TITLE
where is the 3.1 release?

### ISSUE THREAD

**Issue by otrosien** [SonarQubeCommunity/sonar-clover#7]
I can't find it either on the github releases page, nor on the sonarqube site ( http://downloads.sonarsource.com/plugins/org/codehaus/sonar-plugins/ ) and 3.0 does not work on a sonarqube 5.4....

**Comment by benzonico** [comment]
You can find the 3.1 release on maven central : http://search.maven.org/#artifactdetails%7Corg.sonarsource.clover%7Csonar-clover-plugin%7C3.1%7Csonar-plugin 

And it should be available through update center.
